/// <reference types="nativewind/types" />

declare module "react-native" {
  interface ViewProps {
    className?: string;
  }
  interface TextProps {
    className?: string;
  }
  interface ImageProps {
    className?: string;
  }
  interface ScrollViewProps {
    className?: string;
  }
  interface TouchableOpacityProps {
    className?: string;
  }
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.