/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/DummyData`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/InputHandle`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Routing`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Scrollview`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Stylesheet`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/About`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Contact`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/DummyData`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/InputHandle`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/Navbar`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/Routing`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/Scrollview`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/Stylesheet`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/About`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/Contact`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `/src/components/DummyData${`?${string}` | `#${string}` | ''}` | `/src/components/InputHandle${`?${string}` | `#${string}` | ''}` | `/src/components/Navbar${`?${string}` | `#${string}` | ''}` | `/src/components/Routing${`?${string}` | `#${string}` | ''}` | `/src/components/Scrollview${`?${string}` | `#${string}` | ''}` | `/src/components/Stylesheet${`?${string}` | `#${string}` | ''}` | `/src/screens/About${`?${string}` | `#${string}` | ''}` | `/src/screens/Contact${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/DummyData`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/InputHandle`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Routing`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Scrollview`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/Stylesheet`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/About`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/Contact`; params?: Router.UnknownInputParams; };
    }
  }
}
